<%= dockerfile_header %>

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app

RUN bundle install \
&& bundle exec rake db:create \
&& bundle exec rake db:migrate \
&& bundle exec rake db:seed

EXPOSE 3000
