FROM centurylink/flatcar-base

RUN curl --silent --location https://deb.nodesource.com/setup_0.12 | bash - && apt-get install -y nodejs
RUN bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:seed && bundle exec rails s